movie1/urls.py
from django.conf.urls import url
from . import views
app_name = 'movie1'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<movie_id>[0-9]+)/$',views.detail,name='detail'),
    #/movie1/<a.id>/favourite/
    url(r'^(?P<movie_id>[0-9]+)/favourite/$',views.favourite,name='favourite'),
    #url('db',views.index1,name=''),
    #Authentication creativity
    #url('login/',views.user_login,name="user_login"),
    #url('success/',views.success,name="user_success"),
    #url('logout/',views.user_logout,name="user_logout"),

]

shiv1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('movie1.urls')),
]

movie1/models.py
from django.db import models

class Movie(models.Model):
    actor = models.CharField(max_length=30)
    actor_movie  = models.CharField(max_length=50)
    genre = models.CharField(max_length=20)
    movie_logo = models.CharField(max_length=100)

    def __str__(self):
        return self.actor + '----' + self.actor_movie

class Song(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=50)
    song_name  = models.CharField(max_length=100)
    is_favourite=models.BooleanField(default = False)

    def __str__(self):
        return self.song_name

movie1/views.py
from django.shortcuts import render, get_object_or_404
from . models import Movie,Song
#from django.http import HttpResponse
from django.http import Http404
from django .template import loader

def index(request):
    all_movies= Movie.objects.all()
    template = loader.get_template('movie1/index.html')
    context = {
      'all_movies':all_movies,
    }
    #for a in all_movies:
        #url = '/movie1/'+ str(a.id) + '/'
        #html = '<a href = " '+ url + ' ">' + a.actor + '</a><br>'
    return render(request,'movie1/index.html',context)

def detail(request, movie_id):
    #return HttpResponse("<h2>welcome in id :" + str(movie_id) + "</h2>")
    m1=get_object_or_404(Movie, pk=movie_id)
    return render(request,'movie1/index1.html', {'m1':m1})

def favourite(request, movie_id):
    m1 = get_object_or_404(Movie, pk=movie_id)
    try:
        selected_song = m1.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request,'movie1/index1.html', {'m1':m1,
                                   'error_message':"You did not select song"})
    else:
        selected_song.is_favourite=True
        selected_song.save()
        return render(request,'movie1/index1.html', {'m1':m1})

movie1/templates/movie1/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>django project</title>
    <link rel="stylesheet" type="text/css" href="{% static 'movie1/style.css' % }">
  </head>
  <body>
    <ul>
      {% for a in all_movies %}
      <li>
        <a href="{% url 'movie1:detail' a.id %}"> {{ a.actor }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </body>
</html>

movie1/templates/movie1/index1.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{ m1.actor }}</h1>
    <h1>{{ m1.actor_movie }}</h1>
    {% if error_message %}
    <strong>{{ error_message }}</strong>
    {% endif %}
    <form class="" action="{% url 'movie1:favourite' m1.id %}" method="post">
      {% csrf_token %}
      {% for song in m1.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
      <label for="song{{ forloop.counter }}">
        {{ song.song_name }}
        {% if song.is_favourite %}
         <img src="C:\Users\SHIV SHARMA\Downloads\shakti_mohan.jpg" alt=""/>
        {% endif %}
      </label><br>
      {% endfor %}
      <input type="submit" name="" value="favourite">
    </form>
  </body>
</html>